### ISSUE TITLE
Milestone 1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_BlackFriday_Purchases_Analysis#42]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] No need to show the formulas for common statistics such as SE and confidence interval. 

**Reasoning**
Great job!

**Visualization**
- [x] I don't understand what the axes mean in figures 2 and 3. What do the bars represent/ 
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"

**Quality -- Readability and Documentation**
Great job!

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each function (other than the main function)

**Grammar and Spelling**
_README.md_
- [x] Misspelled decision, Acknowledgments, cleaning 
- [x] Missing a few definite/indefinite articles. 
_Report_
- [x] Misspelled project, population, purchase

**Comment by aimirza** [comment]
You need the definite article "the" or indefinite article "a" before some nouns.

**Comment by mru4913** [comment]
Thank you @aimirza. We updated based on your feedback. This issue is closed.

**Comment by aimirza** [comment]
You still need to create unit tests for functions other than the main function. You have several functions in your scripts. You dont need a unit test for the main(). 

- [ ] Please state the actual P-value. 

One issue in your Makefile. Step 4 has an issue. Your inputs results/blackfriday_est.csv and results/t_test_result.csv are listed but they are not fed into the script. Why is that? Please make it more clear.

**Comment by gilbertlei** [comment]
> You still need to create unit tests for functions other than the main function. You have several functions in your scripts. You dont need a unit test for the main().
> 
> * [ ]  Please state the actual P-value.
> 
> One issue in your Makefile. Step 4 has an issue. Your inputs results/blackfriday_est.csv and results/t_test_result.csv are listed but they are not fed into the script. Why is that? Please make it more clear.

We solved the issue with Makefile Step 4. 

still working on other ones.

**Comment by mru4913** [comment]
I stated the p-value in the report.

**Comment by mru4913** [comment]
I added more unit tests for our project.

**Comment by mru4913** [comment]
problem solved.
